In [6]:
import pandas as pd
import numpy as np
import random as r


# NUMBER 1

In [260]:
# NUMBER 1
dice = 2
rolls = 100

roll = np.random.randint(1, 6, size =(rolls, dice))
roll_double = roll[:,0] == roll[:,1]
percentage = (roll_double).mean()
percentage

0.16

In [265]:
df = pd.DataFrame()
df['roll_one'] = np.random.randint(1,7, 10_000)
df['roll_two'] = np.random.randint(1,7, 10_000)

(df.roll_one == df.roll_two).mean()

0.1695

# NUMBER 2

In [266]:
## NUMBER 2
# creating 3 coinflips either head 1, or tails 0
flip1 = r.choice([1,0])
flip2 = r.choice([1,0])
flip3 = r.choice([1,0])

# Let's see the flip outcomes next to each other

flip1, flip2, flip3

(0, 1, 0)

In [112]:
# A quicker way to do this with numpy.
# We want random flips for 1 or 0 and 8 total flips
flip8 = np.random.choice([1,0], size = (80000)).reshape(10000, 8)
flip8


array([[0, 0, 0, ..., 1, 0, 0],
       [1, 1, 1, ..., 0, 1, 0],
       [0, 1, 1, ..., 1, 1, 1],
       ...,
       [0, 0, 1, ..., 1, 0, 1],
       [0, 0, 1, ..., 1, 1, 0],
       [0, 1, 1, ..., 1, 1, 0]])

In [113]:
#Checking through each row and adding up how many head flips we got
headcount = flip8.sum(axis=1)
headcount

array([2, 5, 6, ..., 4, 5, 6])

In [114]:
# checking through each test and counting how many heads "1" we get

head_flips = headcount >= 3
head_flips

array([False,  True,  True, ...,  True,  True,  True])

In [115]:
#Lets make a bigger test 
head_flips.mean()

0.8575

# NUMBER 3


In [196]:
## NUMBER 3
# choice allows a little more clarity than uniform will, easier for review
#Create a process of random cohort selection
# data_sci = .25
# billboard = 2
# data = 1
# web_dev = 3


select_cohort = np.random.choice([1,3,3,3], 10000 * 2).reshape(10000,2)
select_cohort

outcome = select_cohort.sum(axis=1)
# If the sum of each equals to '2' I know it is 2 data sci billboards
data_sci = outcome == 2
data_sci.mean()

0.0664

In [271]:
simulations =np.random.choice(['web dev', 'data sci'], p = (.75, .25), size =(10000, 2))
simulations

((simulations == 'data sci').sum(axis = 1) == 2).mean()

0.0616

# NUMBER 4

In [279]:
std = 1.5
pop_avg = 3
# Using random.normal to set the poptarts bought and std for mon-fri
bought = np.random.normal(pop_avg, std, size =(10000,4))
# adding up total bought from mon-thur(1-4) 
consumed = bought.sum(axis=1)
# finding the number of poptarts left after thursday
remaining = 17 - consumed

(remaining >=1).mean()

0.9063

In [278]:
#round afterwards to get rid of floats
purchases = np.random.normal(3,1.5, size =(10000, 4)).round()
# where function used to rid of negative numbers and use 0 instead
purchases = np.where(purchases<0, 0, purchases)
(purchases.sum(axis =1)<= 16).mean()

0.9317

# NUMBER 5

In [208]:
m = 178
mstd = 8

w = 170
wstd = 6

#Getting the average height of men and women over 10,0000 measurements
heightm = np.random.normal(m, mstd, size =(10000))

heightw = np.random.normal(w, wstd, size =(10000))

# checking the percentage of woment being taller than men
tallerw = (heightw > heightm).mean()
tallerw

0.2151

In [282]:
mensh = np.random.normal(178, 8, 10000)

womensh =np.random.normal(170, 6, 10000)

(womensh > mensh).mean()



0.2142

# NUMBER 6

In [238]:
corrupted = (1/250)

studentn = 50
simulation = 10000

# allows me to see random outcomes for # of simulations ran per student
test = np.random.random([simulation,studentn])
# we are now specifying a value of error where the test # less than chance of currupt downloads
error = test < corrupted
# check for the number of downloads with absolutely NO errors '=='
clean_dwnld = (error.sum(axis=1) ==0).mean()
clean_dwnld

0.8123

In [241]:
studentsn = 150

test2 = np.random.random([simulation,studentsn])

error = test < corrupted
cleanly = (error.sum(axis = 1) == 0).mean()
issue_observe = 1 - cleanly 
issue_observe

0.18769999999999998

In [284]:
nstudents = 50

simulations = np.random.choice([True, False], p=(1/250, 249/250), size =(10000, nstudents))
# for every row look up values, if any value is true give 1, if false give 0
(simulations.sum(axis =1) == 0).mean()

0.8234

In [286]:
1-simulations.any(axis=1).mean()

0.8234

In [291]:
nstudents = 150

simulations = np.random.choice([True, False], p=(1/250, 249/250), size =(10000, nstudents))
# for every row look up values, if any value is true give 1, if false give 0
(simulations.any(axis =1)).mean()

0.4426

In [292]:
nstudents = 450

simulations = np.random.choice([True, False], p=(1/250, 249/250), size =(10000, nstudents))
# for every row look up values, if any value is true give 1, if false give 0
(simulations.sum(axis =1) == 0).mean()

0.1567

# NUMBER 7

In [254]:
truck_present = .7 #percentage
no_sighting = 3 #days


travis_ft = np.random.random([10000, no_sighting])
travis_ft
# likely = travis_ft < truck_present
# not_there = (likely.sum(axis=1) == 0).mean()
# not_there

array([[0.11479029, 0.42700932, 0.62641349],
       [0.09760497, 0.59578574, 0.46534556],
       [0.71791062, 0.56361567, 0.81008805],
       ...,
       [0.0775306 , 0.86657301, 0.15303149],
       [0.54629492, 0.6705569 , 0.86916755],
       [0.15081797, 0.9432326 , 0.83427042]])

In [256]:
#getting booleans for travis a foodtruck not being present based on chance
likely = travis_ft < truck_present
likely

array([[ True,  True,  True],
       [ True,  True,  True],
       [False,  True, False],
       ...,
       [ True, False,  True],
       [ True,  True, False],
       [ True, False, False]])

In [257]:
# discovering the percentage for a foodtruck being present for 3 days
not_there = (likely.sum(axis=1) == 0).mean()
not_there

0.0274

In [297]:
simulations = np.random.choice(['food truck', 'no food truck'], p =(.7, .3), size = (10000, 3))

(simulations =='no food truck').all(axis=1).mean()

0.0257

In [ ]:
simulations.np.random.choice['food truck', 'no food truck'], p =(.7, .3), size = (10000, 3))

# NUMBER 8

In [303]:
simulations = np.random.randint(1,366, size = (10000, 23))
simulations = pd.DataFrame(simulations)
(simulations.apply(lambda birthdays:birthdays.nunique(), axis =1)< 23).mean()

0.5115

In [304]:
simulations = np.random.randint(1,366, size = (10000, 20))
simulations = pd.DataFrame(simulations)
(simulations.apply(lambda birthdays:birthdays.nunique(), axis =1)< 20).mean()

0.419

In [306]:
simulations = np.random.randint(1,366, size = (10000, 50))
simulations = pd.DataFrame(simulations)
(simulations.apply(lambda birthdays:birthdays.nunique(), axis =1)< 50).mean()

0.9717